linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - gosec
    - revive
    - exhaustive
    - wrapcheck
    - gocognit
    - unused
    - misspell

linters-settings:
  gosec:
    severity: high
    excludes:
      - G204
